export const CLEAR_ERRORS = "CLEAR_ERRORS"

export const userConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",

    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAIL: "LOGOUT_FAIL",

    LOAD_USER_REQUEST: "LOAD_USER_REQUEST",
    LOAD_USER_SUCCESS: "LOAD_USER_SUCCESS",
    LOAD_USER_FAIL: "LOAD_USER_FAIL",

    REGISTER_USER_REQUEST: "REGISTER_USER_REQUEST",
    REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
    REGISTER_USER_FAIL: "REGISTER_USER_FAIL",
    REGISTER_USER_RESET: "REGISTER_USER_RESET",

    FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST",
    FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
    FORGOT_PASSWORD_FAIL: "FORGOT_PASSWORD_FAIL",
    FORGOT_PASSWORD_RESET: "FORGOT_PASSWORD_RESET",

    NEW_PASSWORD_REQUEST: "NEW_PASSWORD_REQUEST",
    NEW_PASSWORD_SUCCESS: "NEW_PASSWORD_SUCCESS",
    NEW_PASSWORD_FAIL: "NEW_PASSWORD_FAIL",
    NEW_PASSWORD_RESET: "NEW_PASSWORD_RESET",

    UPDATE_PASSWORD_REQUEST: "UPDATE_PASSWORD_REQUEST",
    UPDATE_PASSWORD_SUCCESS: "UPDATE_PASSWORD_SUCCESS",
    UPDATE_PASSWORD_FAIL: "UPDATE_PASSWORD_FAIL",
    UPDATE_PASSWORD_RESET: "UPDATE_PASSWORD_RESET",

    ALL_USERS_REQUEST: "ALL_USERS_REQUEST",
    ALL_USERS_SUCCESS: "ALL_USERS_SUCCESS",
    ALL_USERS_FAIL: "ALL_USERS_FAIL",

    USER_DETAILS_REQUEST: "USER_DETAILS_REQUEST",
    USER_DETAILS_SUCCESS: "USER_DETAILS_SUCCESS",
    USER_DETAILS_FAIL: "USER_DETAILS_FAIL",

    UPDATE_USER_REQUEST: "UPDATE_USER_REQUEST",
    UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
    UPDATE_USER_FAIL: "UPDATE_USER_FAIL",
    UPDATE_USER_RESET: "UPDATE_USER_RESET",

    DELETE_USER_REQUEST: "DELETE_USER_REQUEST",
    DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
    DELETE_USER_FAIL: "DELETE_USER_FAIL",
    DELETE_USER_RESET: "DELETE_USER_RESET"
}

export const auditConstants = {
    ALL_AUDITS_REQUEST: "ALL_AUDITS_REQUEST",
    ALL_AUDITS_SUCCESS: "ALL_AUDITS_SUCCESS",
    ALL_AUDITS_FAIL: "ALL_AUDITS_FAIL",
}

export const categoryConstants = {
    GET_CATEGORIES_REQUEST: "GET_CATEGORIES_REQUEST",
    GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
    GET_CATEGORIES_FAIL: "GET_CATEGORIES_FAIL",
    GET_CATEGORIES_RESET: "GET_CATEGORIES_RESET",

    NEW_CATEGORY_REQUEST: "NEW_CATEGORY_REQUEST",
    NEW_CATEGORY_SUCCESS: "NEW_CATEGORY_SUCCESS",
    NEW_CATEGORY_FAIL: "NEW_CATEGORY_FAIL",
    NEW_CATEGORY_RESET: "NEW_CATEGORY_RESET",

    DELETE_CATEGORY_REQUEST: "DELETE_CATEGORY_REQUEST",
    DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORY_SUCCESS",
    DELETE_CATEGORY_FAIL: "DELETE_CATEGORY_FAIL",
    DELETE_CATEGORY_RESET: "DELETE_CATEGORY_RESET"
}

export const productConstants = {}
export const serviceConstants = {}